### ISSUE TITLE
missing mkdirp dependency

### ISSUE THREAD

**Issue by kotarac** [maxtaco/coffee-script#178]
The CLI is erroring out after that runtime dependency removal yesterday.

```
stipe@pro ~ $ npm -g i iced-coffee-script@latest
/usr/local/bin/icake -> /usr/local/lib/node_modules/iced-coffee-script/bin/cake
/usr/local/bin/iced -> /usr/local/lib/node_modules/iced-coffee-script/bin/coffee
iced-coffee-script@108.0.10 /usr/local/lib/node_modules/iced-coffee-script
└── iced-runtime@1.0.3
stipe@pro ~ $ iced
module.js:327
    throw err;
    ^

Error: Cannot find module 'mkdirp'
  at Function.Module._resolveFilename (module.js:325:15)
  at Function.Module._load (module.js:276:25)
  at Module.require (module.js:353:17)
  at require (internal/module.js:12:17)
  at Object.<anonymous> (/usr/local/lib/node_modules/iced-coffee-script/lib/coffee-script/command.js:16:12)
  at Object.<anonymous> (/usr/local/lib/node_modules/iced-coffee-script/lib/coffee-script/command.js:589:4)
  at Module._compile (module.js:409:26)
  at Object.Module._extensions..js (module.js:416:10)
  at Module.load (module.js:343:32)
  at Function.Module._load (module.js:300:12)
  at Module.require (module.js:353:17)
  at require (internal/module.js:12:17)
  at Object.<anonymous> (/usr/local/lib/node_modules/iced-coffee-script/bin/coffee:7:1)
  at Module._compile (module.js:409:26)
  at Object.Module._extensions..js (module.js:416:10)
  at Module.load (module.js:343:32)
  at Function.Module._load (module.js:300:12)
  at Function.Module.runMain (module.js:441:10)
  at startup (node.js:139:18)
  at node.js:968:3
```

**Comment by maxtaco** [comment]
On it... sorry for the breakage...

**Comment by maxtaco** [comment]
Ok, try v108.0.11

Sorry about that!

**Comment by kotarac** [comment]
That fixed it, thanks!
